services:
  search-results-summarizer:
    image: search-results-summarizer
    build: ./search-results-summarizer
    container_name: search-results-summarizer
    ports:
      - "3000:3000"
    environment:
      - ENGINE_NAME=searxng # "searxng" or "4get"
      - ENGINE_URL=http://172.17.0.1:8888 # searxng or 4get instance url
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OPENROUTER_MODEL=${OPENROUTER_MODEL}
      - SUMMARY_ENABLED=true
      - MAX_RESULTS_FOR_SUMMARY=7
    restart: unless-stopped
